/*  AUTERIZACION Y LOGIN */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const RECOVERY_PASSWORD = "RECOVERY_PASSWORD";
// Carrito
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_DB ="DELETE_CART_DB"; 
export const DELETE_ITEM = "DELETE_ITEM";
export const GET_CART ="GET_CART";
export const REST_ITEM = "REST_ITEM";
export const UPDATE_CART = "UPDATE_CART";