/*  AUTERIZACION Y LOGIN */

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const RECOVERY_PASSWORD = "RECOVERY_PASSWORD"

export const SEARCH_BY_NAME= "SEARCH_BY_NAME";
export const ORDER_BY_PRICE="ORDER_BY_PRICE";
export const ORDER_BY_RATE= "ORDER_BY_RATE";
export const FILTER_BY_CATEGORY= "FILTER_BY_CATEGORY";


export const GET_CATEGORIES="GET_CATEGORIES";


